# Generated by Django 4.1.5 on 2023-01-05 13:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y')),
                ('cidade', models.CharField(max_length=30)),
                ('salario', models.FloatField()),
                ('localidade', models.CharField(max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.categoria')),
            ],
        ),
    ]
